language: python

matrix:
  include:
    # use macOS since building pandas wheels takes ages on linux
    # - name: "MacOS py27"
    #   os: osx
    #   language: generic
    #   env:
    #     - PIP=pip2
    #     - CIBW_BUILD="cp27-*"
    #     - COVER="off"

    - name: "MacOS py36"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp36-*"
        - COVER="on"

env:
  global:
    - TWINE_USERNAME=geostatframework

script:
  # create wheels
  - sudo $PIP install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
  # create source dist for pypi and create coverage (only once for linux py3.6)
  - |
    if [[ $COVER == "on" ]]; then
      rm -rf dist
      python -m pip install -U setuptools
      python -m pip install pytest-cov coveralls
      python -m pip install -r docs/requirements.txt
      python setup.py sdist
      python -m pytest --cov ogs5py --cov-report term-missing -v tests/
      python -m coveralls
    fi

after_success:
  # pypi upload (test allways and official on TAG)
  - python -m pip install twine
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload --skip-existing wheelhouse/*.whl
      python -m twine upload --skip-existing dist/*.tar.gz
    fi

notifications:
  email:
    recipients:
    - info@geostat-framework.org
