language: python

matrix:
  include:
    # separate sdist and coverage with py36 on linux
    - name: "sdist and coverage"
      sudo: required
      language: python
      python: 3.6
      services: docker
      script:
        - python -m pip install -U setuptools pytest-cov coveralls
        - python setup.py sdist -d dist
        - python -m pip install -r requirements.txt
        - python -m pytest --cov ogs5py --cov-report term-missing -v tests/
        - python -m coveralls
    # universal wheel on 64bit Linux with py36
    - name: "py2.py3 wheel"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp36-*64"

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install setuptools"

script:
  # create wheels
  - python -m pip install cibuildwheel==1.0.0
  - python -m cibuildwheel --output-dir dist

after_success:
  - python -m pip install twine
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload --verbose --skip-existing dist/*; fi

notifications:
  email:
    recipients:
      - info@geostat-framework.org
