language: python

matrix:
  include:
    # separate sdist and coverage with py36 on linux
    - name: "sdist and coverage"
      sudo: required
      language: python
      python: 3.6
      services: docker
      script:
        - python -m pip install -U setuptools pytest-cov coveralls
        - python setup.py sdist -d wheelhouse
        - python -m pip install -r requirements.txt
        - python -m pytest --cov ogs5py --cov-report term-missing -v tests/
        - python -m coveralls
    # universal wheel on 64bit Linux with py36
    - name: "Linux py36"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp36-*_x86_64"

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install setuptools"
    - CIBW_TEST_REQUIRES=pytest
    # no "__init__.py" in tests/ to run tests against installed wheel
    # https://doc.pytest.org/en/3.0.4/goodpractices.html#choosing-a-test-layout-import-rules
    - CIBW_TEST_COMMAND="python -m pytest -v {project}/tests"

script:
  # create wheels
  - python -m pip install cibuildwheel==0.12.0
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # pypi upload (test allways and official on TAG)
  - python -m pip install twine
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload --skip-existing wheelhouse/*.whl
    fi

notifications:
  email:
    recipients:
    - info@geostat-framework.org
